version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: aula_prova
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      POSTGRES_DB: aula_prova
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  pgdata:
